//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::metric::Entity as Metric;
pub use super::pupil::Entity as Pupil;
pub use super::record::Entity as Record;
pub use super::user::Entity as User;
